name: Build Flow

on: 
  push: 
    branches:
      - patch/ostruct-1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm-version: [ '1.12.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
            submodules: recursive

      - name: Setup SourcePawn ${{ matrix.sm-version }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}

      - name: Setup Build Env
        run: |
          mkdir -p build/ccp build/include

          cp -r -f ccp-* build/
          cp -r -f ccp/* build/ccp/
          cp -r -f include/* build/include/

          cp -r -f third-party/packager/include/* build/include/
          cp -r -f third-party/storage/src/include/*  build/include/
          cp -r -f third-party/sm-jansson/pawn/scripting/include/*  build/include/
          cp -r -f third-party/shop/addons/sourcemod/scripting/include/* build/include/
          cp -r -f third-party/vip/addons/sourcemod/scripting/include/* build/include/

          for dir in build/ccp-*/; do
            mkdir -p "$dir/plugins" 2>/dev/null
          done

          mkdir -p build/ccp/plugins

      - name: Build All
        working-directory: build   
        run: |
          for dir in ccp-*/; do
            folder_name=$(basename "$dir")

            s_file=$folder_name/scripting/$folder_name.sp
            o_file=$folder_name/plugins/$folder_name.smx

            echo "Compiling $s_file ..."

            spcomp $s_file -O2 -v2 -iinclude -o $o_file
          done
            