name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm-version: [ '1.11.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: build

      - uses: actions/checkout@v3

      - name: Setup SourcePawn
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}

      - name: Setup Working Directory
        run: |
          mkdir -p sourcemod/plugins
          mkdir -p sourcemod/scripting

          cp -r -f src/* sourcemod/scripting/
          
      - name: Build Packager
        working-directory: src
        run: |
          for file in *.sp;
          do
            filename=$(basename -- "$file")

            echo "\nCompiling $filename..."
          done

      - name: Upload Packager
        uses: actions/upload-artifact@v3
        with: 
          name: ccprocessor-${{ matrix.sm-version }}
          path: sourcemod

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm-version: [ '1.11.x' ]

    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Package artifact
        run: |
          version=`echo $GITHUB_REF | sed "s/refs\/tags\///"`
          7z a packager-${version}.${{ github.run_number }}.zip ./packager-${{ matrix.sm-version }}/*
      
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*.zip'
          tag: ${{ github.ref }}
          file_glob: true